sudo: false
language: java
jdk:
- openjdk8
- openjdk11
- openjdk12
- openjdk13
- openjdk14
- openjdk-ea
matrix:
  allow_failures:
  - jdk: openjdk-ea
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dshade=true -B -V
before_script:
- mvn versions:display-dependency-updates versions:display-plugin-updates
script:
- mvn test -B
- WATSET=$PWD/target/watset.jar make -C examples CommandLine
- bash -c 'shopt -s globstar nullglob; shellcheck **/*.{sh,ksh,bash}'
after_success:
- mvn javadoc:javadoc
env:
  global:
    secure: GZtDnQnxVkaK71c2Ic3KOTE8YkibNsRd6sC2kVVV6pyxAC5AeLWNAblRskko0Z1nZCVIMxQGMEF+P/OYKXon6ZU0qu0ngjuL1iSbpXnxVXhVYhNPuJS2Il+oMd5QMAViecgHUPPaREMc/iichMH/PAOm4gpvkRXSTYLaztkXr16uO49iv028hFIGgfBx5o9urhL3t/f1nZWkBgO5D4RSSeR1NbHA3kXm8IQ5lxvS1lOZ5KaiAEn72ADPogu0wcBD1if7p7iZPp8TCpQ6gGXgA3byC9NbGlep+VJhE5drAffjv9R57BLFppYaPZWD9xIv3On7vONW2c2qxN1OpdzTzn9a+kqdvpK98ykhEL6V5BSbO/LwsVPztq/smG753j6+5u0k3l7tz06XrY/ssob4jb2d+04MuBq6p2KPnKiyEE/hlsqJ0mKDAjRA6xa4I59CKUdUEVDyd4LQoasf4LVzmFozijGPutH2hFYO2d5Ye7yWaXe1vg1pDnSfTjTh5/3RlHY1W6+al/qbIagJ7Lo55+8sIA8FllQdC7TYvA2RnjVmmygndTpdHjQYlNLFju0wOu5vVbe81ajLKaTl7/sr8YwjpjzLgT1FDq9sVnqKW042a2baqH6jcY9FvjQabUm9pMMUMPQoLe8cuzHeTxRYS6mzJhEIXc+IGrKn1x0nwCY=
cache:
  directories:
  - "$HOME/.m2"
- provider: pages
  local-dir: target/site/apidocs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    jdk: openjdk-ea
    repo: nlpub/watset-java
