sudo: false
language: java
jdk:
- openjdk8
- openjdk11
- openjdk12
- openjdk13
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dshade=true -B -V
before_script:
- mvn versions:display-dependency-updates versions:display-plugin-updates
after_success:
- mvn javadoc:javadoc
env:
  global:
    secure: GZtDnQnxVkaK71c2Ic3KOTE8YkibNsRd6sC2kVVV6pyxAC5AeLWNAblRskko0Z1nZCVIMxQGMEF+P/OYKXon6ZU0qu0ngjuL1iSbpXnxVXhVYhNPuJS2Il+oMd5QMAViecgHUPPaREMc/iichMH/PAOm4gpvkRXSTYLaztkXr16uO49iv028hFIGgfBx5o9urhL3t/f1nZWkBgO5D4RSSeR1NbHA3kXm8IQ5lxvS1lOZ5KaiAEn72ADPogu0wcBD1if7p7iZPp8TCpQ6gGXgA3byC9NbGlep+VJhE5drAffjv9R57BLFppYaPZWD9xIv3On7vONW2c2qxN1OpdzTzn9a+kqdvpK98ykhEL6V5BSbO/LwsVPztq/smG753j6+5u0k3l7tz06XrY/ssob4jb2d+04MuBq6p2KPnKiyEE/hlsqJ0mKDAjRA6xa4I59CKUdUEVDyd4LQoasf4LVzmFozijGPutH2hFYO2d5Ye7yWaXe1vg1pDnSfTjTh5/3RlHY1W6+al/qbIagJ7Lo55+8sIA8FllQdC7TYvA2RnjVmmygndTpdHjQYlNLFju0wOu5vVbe81ajLKaTl7/sr8YwjpjzLgT1FDq9sVnqKW042a2baqH6jcY9FvjQabUm9pMMUMPQoLe8cuzHeTxRYS6mzJhEIXc+IGrKn1x0nwCY=
cache:
  directories:
  - "$HOME/.m2"
deploy:
- provider: releases
  api_key:
    secure: KD+OUHRDfiWWUGeVThdIbyQyglHLno49xqydKEWwUt4rY7F4wbofI8bkYTWg4PqGreKdMD6rJguFBeVXqSCfwkC6DkAqc1BXmglpN8vRqEhYYmjTIQrSoPQrdm/a5sRNNHzueM4XMK9Kqzo2f1K2pEzmSB0CyPfsLCBBa+Hdo72Z8Ev5s2kreZznmMLULd9jr8HUNpnQiXPNUGHA+KTOx5x340Si2sINUY9LJfyH3qLe2f7X4pILg+lLZZ1rnkXLgvvgw/beu1VcFmhzWwSkzPCJ303aMCJiMCYMKHPJSCu0UaDPnWvfRtdNS9ISzCC/QA2xtPPM4ZHk78qYwydqyccl/doIbMS5nUJ7qPACqW4hcddwYAOLH6hqnIBLHdOqOsUm5aN3/thopmnGJ9Q5c08PETBcIEXaZjnU6b3DzAa+UG6sWMTjzJg3XgcdG7Fkz7fS7dzrXu9oUwlYUyydwkJ608sMShX/6MCIMwPhZGNGUA+UQhfutPv5+5ElQjuHImRqvVrXA2DxQykuwF+ce6d+G9G2gnzzDoYcJQbdhFi53biMBGwg+ur6ddITRVSB5BflQHLoGqNJeeDjfj0CoSeAhr+gWoG8vF+AsLnOxcjd2fKBSmq6BoL6CPcnifatDJxtl+P4078IYCax33Be3iqP8hTZQX7E82IRxPMZhdA=
  file: target/watset.jar
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
    repo: nlpub/watset-java
- provider: pages
  local-dir: target/site/apidocs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    jdk: openjdk13
    repo: nlpub/watset-java
